services:
  matching-engine:
    build: .
    ports:
      - 3000:3000
    environment:
      RUST_LOG: info

  prometheus:
    image: prom/prometheus:v2.40.4
    depends_on:
      - matching-engine
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.3.0
    depends_on:
      - prometheus
    volumes:
      - ./config/provisioning:/etc/grafana/provisioning:ro
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SERVER_HTTP_PORT: 9091
    restart: unless-stopped
    ports:
      - 9091:9091
