### Get orderbook
GET http://localhost:3000/

### Post login
POST http://localhost:3000/login
Content-Type: application/json

{
  "userId": "{{$random.uuid}}"
}

> {%
  // Store received token
  client.global.set("token", response.body.token);
%}

### Get user info
GET http://localhost:3000/me
Authorization: Bearer {{token}}

### Get trades
GET http://localhost:3000/trades

### Get orders
GET http://localhost:3000/

### Place a selling order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "price": 20,
  "quantity": 250,
  "side": "Sell",
  "order_type": "Limit"
}

### Place a buying order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "price": 22,
  "quantity": 500,
  "side": "Buy",
  "order_type": "Limit"
}
